default_context:
  name: "ccapi"
  version: "0.1.0"
  slug: "ccapi"
  command: "ccapi"
  cli: "argparse"
  config: "y"
  compat: "custom"
  jupyter: "n"
  sqlite: "y"
  pypy: "y"
  travis: "n"
  appveyor: "n"
  description: "Python API for Cell Collective"
  author: "Achilles Rasquinha"
  email: "achillesrasquinha@gmail.com"
  keywords: "ccapi model cell collective"
  license: "MIT License"
  repo_service: "https://github.com"
  repo_service_username: "cellcollective"
  repo_service_reponame: "ccapi"
  docker_service_username: "cellcollective"
  docker_service_reponame: "ccapi"
  github_action: "n"
  ml: "n"
  editor: "vscode"
  url: "https://github.com/cellcollective/ccapi"